CREATE TABLE COLLECTION (
ID TEXT NOT NULL,
BACKED_UP INTEGER DEFAULT 0,
DELETED INTEGER DEFAULT 0,
POSITION INTEGER NOT NULL,
TITLE TEXT,
CREATED DATETIME,
MODIFIED DATETIME
);

CREATE TABLE LINK_ITEM (
ID TEXT NOT NULL,
COLLECTION TEXT,
BACKED_UP INTEGER DEFAULT 0,
DELETED INTEGER DEFAULT 0,
URL TEXT,
TITLE TEXT,
COORDINATES TEXT,
LOCATION TEXT,
CREATED DATETIME,
MOVED DATETIME
);

CREATE TABLE LOCATION_ITEM (
ID TEXT NOT NULL,
COLLECTION TEXT,
BACKED_UP INTEGER DEFAULT 0,
DELETED INTEGER DEFAULT 0,
COORDINATES TEXT,
LOCATION TEXT,
CREATED DATETIME,
MOVED DATETIME
);

CREATE TABLE MEDIA_ITEM (
ID TEXT NOT NULL,
COLLECTION TEXT,
BACKED_UP INTEGER DEFAULT 0,
DELETED INTEGER DEFAULT 0,
TYPE INTEGER,
CAPTION_ANCHOR_POINT TEXT,
CAPTION_BOUNDS TEXT,
CAPTION_CENTER TEXT,
CAPTION_TRANSFORM TEXT,
COORDINATES TEXT,
LOCATION TEXT,
CREATED DATETIME,
MODIFIED DATETIME,
MOVED DATETIME
);

CREATE TABLE TEXT_ITEM (
ID TEXT NOT NULL,
COLLECTION TEXT,
BACKED_UP INTEGER DEFAULT 0,
DELETED INTEGER DEFAULT 0,
COORDINATES TEXT,
LOCATION TEXT,
CREATED DATETIME,
MODIFIED DATETIME,
MOVED DATETIME
);